In [222]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [223]:
dataset=pd.read_csv('C:\\Users\\shubh\\Downloads\\liverpoolfcstats.csv')


In [224]:
X=dataset.iloc[:,2:4]

In [225]:
for a in X:
    a.replace(" ","")

In [226]:
print(X)

      HomeTeam        AwayTeam
0    Liverpool  Sheffield Weds
1          QPR       Liverpool
2      Swindon       Liverpool
3    Liverpool       Tottenham
4    Liverpool           Leeds
..         ...             ...
953  Liverpool     Bournemouth
954  West Brom       Liverpool
955  Liverpool           Stoke
956    Chelsea       Liverpool
957  Liverpool        Brighton

[958 rows x 2 columns]


In [227]:
y=dataset.iloc[:,6].values

In [228]:
print(y)

['H' 'A' 'A' 'A' 'H' 'H' 'A' 'H' 'H' 'D' 'H' 'D' 'H' 'H' 'H' 'H' 'H' 'H'
 'D' 'D' 'D' 'D' 'A' 'D' 'A' 'H' 'D' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'H' 'A'
 'D' 'H' 'A' 'A' 'A' 'H' 'A' 'H' 'A' 'D' 'H' 'D' 'H' 'H' 'H' 'H' 'A' 'H'
 'H' 'H' 'H' 'D' 'D' 'D' 'D' 'A' 'H' 'A' 'H' 'A' 'D' 'D' 'D' 'A' 'H' 'A'
 'H' 'D' 'H' 'A' 'A' 'H' 'H' 'A' 'D' 'H' 'H' 'H' 'H' 'H' 'A' 'H' 'H' 'H'
 'H' 'D' 'D' 'A' 'H' 'H' 'A' 'D' 'H' 'D' 'A' 'H' 'H' 'D' 'H' 'D' 'H' 'A'
 'D' 'A' 'A' 'H' 'D' 'H' 'H' 'H' 'H' 'H' 'D' 'H' 'D' 'D' 'D' 'H' 'D' 'A'
 'H' 'A' 'H' 'A' 'H' 'H' 'H' 'A' 'D' 'D' 'A' 'A' 'H' 'H' 'D' 'D' 'A' 'H'
 'D' 'H' 'A' 'H' 'D' 'H' 'H' 'D' 'A' 'A' 'A' 'D' 'A' 'H' 'H' 'D' 'D' 'A'
 'D' 'A' 'H' 'D' 'H' 'H' 'H' 'H' 'H' 'D' 'H' 'A' 'A' 'A' 'A' 'H' 'H' 'A'
 'H' 'D' 'H' 'D' 'A' 'D' 'D' 'H' 'H' 'D' 'A' 'D' 'H' 'D' 'H' 'H' 'H' 'H'
 'A' 'D' 'A' 'H' 'H' 'D' 'H' 'D' 'D' 'H' 'H' 'A' 'A' 'A' 'H' 'H' 'H' 'H'
 'A' 'H' 'D' 'H' 'H' 'H' 'H' 'D' 'H' 'H' 'H' 'D' 'D' 'A' 'A' 'A' 'H' 'D'
 'H' 'H' 'A' 'A' 'H' 'A' 'H' 'A' 'D' 'A' 'D' 'H' 'D

In [229]:
X['Match']=X['HomeTeam']+X['AwayTeam']


In [230]:
print(X)

      HomeTeam        AwayTeam                    Match
0    Liverpool  Sheffield Weds  LiverpoolSheffield Weds
1          QPR       Liverpool             QPRLiverpool
2      Swindon       Liverpool         SwindonLiverpool
3    Liverpool       Tottenham       LiverpoolTottenham
4    Liverpool           Leeds           LiverpoolLeeds
..         ...             ...                      ...
953  Liverpool     Bournemouth     LiverpoolBournemouth
954  West Brom       Liverpool       West BromLiverpool
955  Liverpool           Stoke           LiverpoolStoke
956    Chelsea       Liverpool         ChelseaLiverpool
957  Liverpool        Brighton        LiverpoolBrighton

[958 rows x 3 columns]


In [231]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 958):
  review = re.sub('[^a-zA-Z]', ' ', X['Match'][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  #all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)
print(corpus)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shubh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['liverpoolsheffield wed', 'qprliverpool', 'swindonliverpool', 'liverpooltottenham', 'liverpoolle', 'coventryliverpool', 'liverpoolblackburn', 'evertonliverpool', 'chelsealiverpool', 'liverpoolarsen', 'liverpoololdham', 'man cityliverpool', 'liverpoolsouthampton', 'liverpoolwest ham', 'newcastleliverpool', 'liverpoolaston villa', 'sheffield wedsliverpool', 'liverpoolqpr', 'liverpoolswindon', 'tottenhamliverpool', 'sheffield unitedliverpool', 'liverpoolwimbledon', 'ipswichliverpool', 'liverpoolman unit', 'oldhamliverpool', 'liverpoolman citi', 'norwichliverpool', 'southamptonliverpool', 'leedsliverpool', 'liverpoolcoventri', 'blackburnliverpool', 'liverpooleverton', 'liverpoolchelsea', 'arsenalliverpool', 'man unitedliverpool', 'liverpoolsheffield unit', 'wimbledonliverpool', 'liverpoolipswich', 'liverpoolnewcastl', 'west hamliverpool', 'liverpoolnorwich', 'aston villaliverpool', 'crystal palaceliverpool', 'liverpoolarsen', 'southamptonliverpool', 'liverpoolwest ham', 'man unitedliverpo

In [232]:
X2=X.iloc[:,2]

In [233]:
print(X2)

0      LiverpoolSheffield Weds
1                 QPRLiverpool
2             SwindonLiverpool
3           LiverpoolTottenham
4               LiverpoolLeeds
                ...           
953       LiverpoolBournemouth
954         West BromLiverpool
955             LiverpoolStoke
956           ChelseaLiverpool
957          LiverpoolBrighton
Name: Match, Length: 958, dtype: object


In [234]:
for match in X2:
    match.replace(" ","")
print(X2)

0      LiverpoolSheffield Weds
1                 QPRLiverpool
2             SwindonLiverpool
3           LiverpoolTottenham
4               LiverpoolLeeds
                ...           
953       LiverpoolBournemouth
954         West BromLiverpool
955             LiverpoolStoke
956           ChelseaLiverpool
957          LiverpoolBrighton
Name: Match, Length: 958, dtype: object


In [235]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X2 = cv.fit_transform(corpus).toarray()


In [236]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# X2 = X2.values.reshape(len(y), 1)
# X2 = np.array(ct.fit_transform(X2))
# print(X2)

In [237]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# X2 = y.reshape(len(X2),1)
# X2 = np.array(ct.fit_transform(X2))
# print(X2)


In [238]:
# trainDfDummies = pd.get_dummies(X2, columns=['Match'])


In [239]:
# print(trainDfDummies)

In [240]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)
y = y.reshape(len(y),1)

[2 0 0 0 2 2 0 2 2 1 2 1 2 2 2 2 2 2 1 1 1 1 0 1 0 2 1 2 2 2 2 2 2 2 2 0 1
 2 0 0 0 2 0 2 0 1 2 1 2 2 2 2 0 2 2 2 2 1 1 1 1 0 2 0 2 0 1 1 1 0 2 0 2 1
 2 0 0 2 2 0 1 2 2 2 2 2 0 2 2 2 2 1 1 0 2 2 0 1 2 1 0 2 2 1 2 1 2 0 1 0 0
 2 1 2 2 2 2 2 1 2 1 1 1 2 1 0 2 0 2 0 2 2 2 0 1 1 0 0 2 2 1 1 0 2 1 2 0 2
 1 2 2 1 0 0 0 1 0 2 2 1 1 0 1 0 2 1 2 2 2 2 2 1 2 0 0 0 0 2 2 0 2 1 2 1 0
 1 1 2 2 1 0 1 2 1 2 2 2 2 0 1 0 2 2 1 2 1 1 2 2 0 0 0 2 2 2 2 0 2 1 2 2 2
 2 1 2 2 2 1 1 0 0 0 2 1 2 2 0 0 2 0 2 0 1 0 1 2 1 2 2 2 0 2 2 2 1 2 2 0 1
 2 0 1 1 1 0 2 0 2 0 1 2 0 1 2 2 2 1 2 2 1 1 2 0 2 2 2 2 2 2 2 0 0 2 2 2 0
 1 1 2 1 2 1 2 1 0 0 2 0 0 2 1 0 2 2 0 0 2 0 1 0 0 2 1 2 0 2 1 2 0 0 1 1 2
 1 1 0 2 0 0 1 0 2 0 2 2 0 2 2 2 2 0 2 1 1 1 0 2 0 2 0 2 2 2 1 2 0 2 2 1 1
 1 2 1 0 1 0 1 2 2 0 2 2 2 0 2 0 0 2 0 1 1 0 0 2 2 0 2 2 0 0 1 2 1 0 2 1 0
 2 2 1 1 1 2 1 2 2 2 1 2 2 0 1 0 2 0 1 1 2 2 2 2 2 2 0 2 1 0 2 2 2 1 2 1 2
 0 2 0 0 0 2 0 2 2 2 1 2 2 2 1 0 2 1 2 2 1 2 1 1 1 0 2 2 2 0 2 0 0 2 2 2 0
 2 1 2 2 1 2 2 0 2 2 1 2 

In [241]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X2, y, test_size = 1/3, random_state = 0)

In [242]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)
# print(X_train)
# print(X_test)

In [243]:
# from sklearn.svm import SVC
# classifier = SVC(kernel = 'rbf', random_state = 0)
# classifier.fit(X_train, y_train)

In [244]:
# from sklearn.ensemble import RandomForestClassifier
# classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
# classifier.fit(X_train, y_train)

In [245]:
# y_pred = classifier.predict(X_test)
# # print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


In [246]:
# from sklearn.metrics import confusion_matrix, accuracy_score
# cm = confusion_matrix(y_test, y_pred)
# print(cm)
# accuracy_score(y_test, y_pred)

In [247]:
# I=input('Enter match as LiverpoolLeeds')
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# I = le.fit_transform([I])
# I = I.reshape(len(I),1)
# print(sc.transform(I))
# print(classifier.predict(sc.transform(I)))

In [248]:
# from sklearn.naive_bayes import GaussianNB
# classifier = GaussianNB()
# classifier.fit(X_train, y_train)

In [249]:
# I=input('Enter match as LiverpoolLeeds')
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# I = le.fit_transform([I])
# I = I.reshape(len(I),1)
# print(sc.transform(I))
# print(classifier.predict(sc.transform(I)))

In [250]:
# from sklearn.metrics import confusion_matrix, accuracy_score
# cm = confusion_matrix(y_test, y_pred)
# print(cm)
# accuracy_score(y_test, y_pred)

In [255]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

C:\Users\shubh\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


GaussianNB()

In [252]:
# I=input('Enter match as LiverpoolLeeds')

# #I = I.reshape(len(I),1)
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# I = np.array(ct.fit_transform(I))
# I = I.values.reshape(len(I),1)
# print(I)



# #I = I.reshape(len(I),1)
# print(sc.transform(I))
# print(classifier.predict(sc.transform(I)))

In [256]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 2]
 [0 0]
 [1 2]
 [1 0]
 [1 2]
 [1 2]
 [0 2]
 [1 0]
 [0 2]
 [0 1]
 [1 2]
 [0 2]
 [0 0]
 [1 2]
 [1 0]
 [1 2]
 [1 2]
 [1 2]
 [0 1]
 [0 1]
 [1 0]
 [0 2]
 [1 2]
 [1 0]
 [0 1]
 [0 0]
 [1 0]
 [0 1]
 [1 2]
 [1 2]
 [1 2]
 [1 0]
 [1 2]
 [0 2]
 [0 0]
 [1 1]
 [1 2]
 [0 1]
 [1 0]
 [0 2]
 [1 0]
 [2 1]
 [1 2]
 [1 0]
 [1 0]
 [0 2]
 [2 2]
 [1 2]
 [2 2]
 [1 2]
 [0 0]
 [1 0]
 [1 0]
 [0 2]
 [1 2]
 [0 0]
 [0 2]
 [0 2]
 [1 2]
 [1 2]
 [1 2]
 [1 0]
 [0 2]
 [1 0]
 [1 2]
 [1 0]
 [0 1]
 [0 2]
 [1 2]
 [1 2]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [0 1]
 [1 1]
 [1 2]
 [0 0]
 [0 2]
 [0 1]
 [1 2]
 [1 1]
 [1 2]
 [2 0]
 [1 2]
 [1 0]
 [1 2]
 [0 1]
 [1 1]
 [1 1]
 [1 2]
 [0 1]
 [1 2]
 [1 1]
 [1 0]
 [0 2]
 [1 2]
 [0 2]
 [1 1]
 [1 2]
 [1 1]
 [0 0]
 [0 1]
 [0 2]
 [0 2]
 [1 2]
 [1 0]
 [1 2]
 [1 2]
 [1 2]
 [0 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 1]
 [0 1]
 [1 2]
 [1 2]
 [1 1]
 [0 2]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [1 2]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 2]
 [0 0]
 [2 1]
 [1 1]
 [0 0]
 [1 2]
 [1 2]
 [1 2]

0.315625

In [253]:
y_pred = classifier.predict(X_test)

In [254]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 40   4  48]
 [ 22   6  50]
 [ 27  11 112]]


0.49375